image:
  repository: ghcr.io/isityael/karakeep
  tag: ci

env:
  NEXTAUTH_URL: https://keep.example.com
  DISABLE_SIGNUPS: "false"
  DISABLE_PASSWORD_AUTH: "true"

database:
  existingSecret:
    name: karakeep-postgres-app
    keys:
      url: uri

secretEnv:
  NEXTAUTH_SECRET:
    secretName: karakeep-config
    key: nextauth-secret
  MEILI_MASTER_KEY:
    secretName: karakeep-config
    key: meili-master-key
