{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opnsense-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "m0sh1-exporter.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
