apiVersion: v1
kind: Service
metadata:
  name: {{ include "m0sh1-exporter.opnsenseName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "m0sh1-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  ipFamilies: [IPv4, IPv6]
  ports:
    - port: {{ .Values.opnsenseExporter.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "m0sh1-exporter.selectorLabels" . | nindent 4 }}
