matrixUmbrella:
  imageProfile: dhi
  imagePullSecrets:
    - name: docker-hardened-images

ess:
  image:
    pullSecrets:
      - name: docker-hardened-images
  matrixTools:
    image:
      pullSecrets:
        - name: docker-hardened-images
  haproxy:
    image:
      registry: dhi.io
      repository: haproxy
      tag: "3.2@sha256:ac42b0af65997c75761a9467696769ceecb14b58a09476afb1446af6a5400bcc"
      pullSecrets:
        - name: docker-hardened-images
  postgres:
    image:
      registry: dhi.io
      repository: postgres
      tag: "18.4-alpine3.22"
  redis:
    image:
      registry: dhi.io
      repository: valkey
      tag: "9.0.3-alpine3.22"

matrix-appservice-irc:
  waitForRedis:
    image:
      repository: dhi.io/busybox
      tag: "1.37.0-musl"
  postgres:
    image:
      repository: dhi.io/postgres
      tag: "18.4-alpine3.22"
  redis:
    image:
      repository: dhi.io/valkey
      tag: "9.0.3-alpine3.22"
