config:
  data:
    service:
      ci_example:
        options:
          active: false
          interval: 1h
        latest_version:
          type: github
          url: release-argus/Argus

ingress:
  enabled: true
  hosts:
    - host: argus.bogusdomain.test
      paths:
        - path: /
          pathType: Prefix
