{{- if and (not .Values.upstream.enabled) .Values.upstream.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.upstream.secret.name }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{- with .Values.upstream.secret.accessKey }}
  accessKeyID: {{ . | quote }}
  {{- end }}
  {{- with .Values.upstream.secret.secretKey }}
  secretAccessKey: {{ . | quote }}
  {{- end }}
  endpoint: {{ .Values.upstream.secret.endpoint | quote }}
  {{- with .Values.upstream.secret.region }}
  region: {{ . | quote }}
  {{- end }}
{{- end }}
