image:
  repository: ghcr.io/gethomepage/homepage
  tag: v1.13.1
  pullPolicy: IfNotPresent

env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: homepage.bogusdomain.test

rbac:
  enabled: true

serviceAccount:
  create: true
  name: homepage-test
  automount: true

ingress:
  enabled: true
  annotations:
    homepage/name: "Homepage"
    homepage/description: "A modern, secure, highly customizable application dashboard."
    homepage/group: "My Group"
    homepage/icon: "homepage.png"
  hosts:
    - host: homepage.bogusdomain.test
      paths:
        - path: /
          pathType: Prefix
