{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "wakapi.fullname" . }}
  labels:
    {{- include "wakapi.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "wakapi.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path | default "/api/metrics" }}
      interval: {{ .Values.serviceMonitor.interval | default "60s" | quote }}
      {{- with .Values.serviceMonitor.authorization }}
      authorization:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
