strategyType: Recreate

persistence:
  enabled: true
  storageClass: standard
  size: 1Gi

serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus
  authorization:
    type: Bearer
    credentials:
      name: wakapi-metrics-token
      key: token

vmServiceScrape:
  enabled: true
  labels:
    release: prometheus-agent
  authorization:
    type: Bearer
    credentials:
      name: wakapi-metrics-token
      key: token

config:
  server:
    public_url: https://wakapi.bogusdomain.test
  db:
    dialect: sqlite3
  security:
    expose_metrics: true

ingress:
  enabled: true
  hosts:
    - host: wakapi.bogusdomain.test
      paths:
        - path: /
          pathType: Prefix
