apiVersion: v2
name: m0sh1-exporter
description: Network exporters bundle for OPNsense, SNMP, and Proxmox VE
type: application
version: 0.1.13
appVersion: "0.0.15"
kubeVersion: ">=1.28.0-0"
icon: https://opnsense.org/wp-content/themes/flavor/assets/images/opnsense.png
home: https://git.m0sh1.cc/m0sh1/helm-charts
sources:
  - https://github.com/AthennaMind/opnsense-exporter
  - https://github.com/prometheus/snmp_exporter
  - https://github.com/prometheus-pve/prometheus-pve-exporter
maintainers:
  - name: m0sh1
    email: yael@m0sh1.cc
keywords:
  - monitoring
  - opnsense
  - snmp
  - proxmox
  - prometheus
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Allow Helm global values in the chart schema.
dependencies:
  - name: prometheus-snmp-exporter
    alias: snmpExporter
    version: 9.16.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-pve-exporter
    alias: pveexporter
    version: 2.8.0
    repository: https://charts.christianhuth.de
