# yaml-language-server: $schema=values.schema.json

replicaCount: 1
revisionHistoryLimit: 1

nameOverride: ""
fullnameOverride: ""

opnsenseExporter:
  nameOverride: opnsense-exporter
  image:
    repository: ghcr.io/isityael/opnsense-exporter
    tag: "v0.0.15-m0sh1.3@sha256:cd9edc4d87323e2ffb7a068458b2d8550de1f8260deb039ca4c1f81059e798a9"
    pullPolicy: IfNotPresent
  opnsense:
    protocol: https
    address: opnsense.example.com
    instanceLabel: opnsense
    existingSecret: opnsense-exporter-api
    apiKeyKey: api-key
    apiSecretKey: api-secret
  service:
    port: 8080
  serviceMonitor:
    enabled: true
    interval: 30s
    additionalLabels: {}
    metricRelabelings: []
  vmServiceScrape:
    enabled: false
    namespace: ""
    labels: {}
    interval: 30s
    metricRelabelConfigs: []
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

nodeSelector: {}
podAnnotations: {}

snmpExporter:
  fullnameOverride: prometheus-snmp-exporter
  image:
    repository: ghcr.io/isityael/snmp-exporter
    tag: "v0.30.1-m0sh1.1@sha256:4fa66be119a45b23553554833a4a16f16786577b07804654424ea707e224552c"
    pullPolicy: IfNotPresent
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi
  serviceMonitor:
    enabled: false
    namespace: monitoring
    path: /snmp
    scrapeTimeout: 25s
    module:
      - if_mib
    auth:
      - public_v2
    honorLabels: true
    params: []
    selfMonitor:
      enabled: false
  vmServiceScrape:
    enabled: false
    namespace: monitoring
    labels: {}
    path: /snmp
    scrapeTimeout: 25s
    module:
      - if_mib
    auth:
      - public_v2
    selector: {}
    honorLabels: true
    params: []
    selfMonitor:
      enabled: false

pveexporter:
  fullnameOverride: prometheus-pve-exporter
  image:
    registry: docker.io
    repository: prompve/prometheus-pve-exporter
    tag: "3.9.0@sha256:78a58df7a31c9fbee94962cd06422672668529de6421892df9aed4b6cee0757f"
    pullPolicy: Always
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
  env:
    pveAuthType: token
    pveUser: pve-exporter@pve
    pveExistingSecretName: monitoring-pve-exporter
    pveVerifySsl: false
  podAnnotations: {}
  serviceMonitor:
    enabled: true
    additionalLabels: {}
    interval: 30s
    namespace: monitoring
    metricRelabelings:
      - targetLabel: instance
        replacement: prometheus-pve-exporter
    pveTargets: []
  vmServiceScrape:
    enabled: false
    namespace: monitoring
    labels: {}
    interval: 30s
    metricRelabelConfigs:
      - targetLabel: instance
        replacement: prometheus-pve-exporter
    pveTargets: []
