# yaml-language-server: $schema=values.schema.json

replicaCount: 1
revisionHistoryLimit: 1

nameOverride: ""
fullnameOverride: ""

opnsenseExporter:
  nameOverride: opnsense-exporter
  image:
    repository: ghcr.io/yaelmoshi/opnsense-exporter
    tag: "v0.0.15-m0sh1.3@sha256:fdbddeabdb093a1364b9e135e9d0b7a8a09bfc92d5d4f187f16b5bff593a5e6b"
    pullPolicy: IfNotPresent
  opnsense:
    protocol: https
    address: opnsense.example.com
    instanceLabel: opnsense
    existingSecret: opnsense-exporter-api
    apiKeyKey: api-key
    apiSecretKey: api-secret
  service:
    port: 8080
  serviceMonitor:
    enabled: true
    interval: 30s
    additionalLabels: {}
    metricRelabelings: []
  vmServiceScrape:
    enabled: false
    namespace: ""
    labels: {}
    interval: 30s
    metricRelabelConfigs: []
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

nodeSelector: {}
podAnnotations: {}

snmpExporter:
  fullnameOverride: prometheus-snmp-exporter
  image:
    repository: ghcr.io/yaelmoshi/snmp-exporter
    tag: "v0.30.1-m0sh1.1@sha256:e5e1b11b17efa1b0d5fe596ee406c5ae5297f529e510154c4c4a03c98052c2ec"
    pullPolicy: IfNotPresent
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi
  serviceMonitor:
    enabled: false
    namespace: monitoring
    path: /snmp
    scrapeTimeout: 25s
    module:
      - if_mib
    auth:
      - public_v2
    honorLabels: true
    params: []
    selfMonitor:
      enabled: false
  vmServiceScrape:
    enabled: false
    namespace: monitoring
    labels: {}
    path: /snmp
    scrapeTimeout: 25s
    module:
      - if_mib
    auth:
      - public_v2
    selector: {}
    honorLabels: true
    params: []
    selfMonitor:
      enabled: false

pveexporter:
  fullnameOverride: prometheus-pve-exporter
  image:
    registry: docker.io
    repository: prompve/prometheus-pve-exporter
    tag: "3.9.0@sha256:78a58df7a31c9fbee94962cd06422672668529de6421892df9aed4b6cee0757f"
    pullPolicy: Always
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
  env:
    pveAuthType: token
    pveUser: pve-exporter@pve
    pveExistingSecretName: monitoring-pve-exporter
    pveVerifySsl: false
  podAnnotations: {}
  serviceMonitor:
    enabled: true
    additionalLabels: {}
    interval: 30s
    namespace: monitoring
    metricRelabelings:
      - targetLabel: instance
        replacement: prometheus-pve-exporter
    pveTargets: []
  vmServiceScrape:
    enabled: false
    namespace: monitoring
    labels: {}
    interval: 30s
    metricRelabelConfigs:
      - targetLabel: instance
        replacement: prometheus-pve-exporter
    pveTargets: []
