# Default values for gitea-runner.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

# -- Docker-in-Docker sidecar container
dind:
  image:
    repository: docker
    tag: "29.5.3-dind-alpine3.23@sha256:7d85d0eda291f1a7ab6df4a9d1802b5ad4cf9145a088bd11188c78dcb5c7392b"
    pullPolicy: IfNotPresent
  args:
    - --host=unix:///var/run/docker.sock
    - --tls=false
  securityContext:
    privileged: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "2"
      memory: 4Gi

# -- Gitea Actions runner container
runner:
  image:
    repository: gitea/runner
    tag: "2.2.0@sha256:968b93c034b6231be037b8abce159dedbf7eb16adbc79ee2b1555c0eea31a4d3"
    pullPolicy: IfNotPresent
  instanceURL: ""
  registrationTokenSecret: ""
  registrationTokenKey: REGISTRATION_TOKEN
  name: ""
  baseLabels: self-hosted
  jobLabel: ""
  jobImage: ""
  labels: ""
  dataMountPath: /data
  extraEnv: []
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    privileged: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 1Gi

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

daemonConfig:
  registryMirrors: []
  insecureRegistries: []
  features:
    buildkit: true

registryAuthSecret: ""
registryAuthSecretKey: .dockerconfigjson
registryAuthMountPath: /root/.docker/config.json

registryCASecret: ""
registryCAKey: ca.crt
registryCAMounts: []

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

nodeSelector: {}
tolerations: []
affinity: {}
