upstream:
  secret:
    create: false
    name: ci-s3-secret
  storageClass:
    create: false
  tolerations:
    node:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

maintainedImage:
  digest: sha256:cc4c6fc2204fb3cc5b79461d7c50c958d1c104f85081e5e8ca71743303ade996

storageClasses:
  - name: csi-s3-ci
    reclaimPolicy: Retain
    bucket: csi-s3-ci
    mountOptions: "--memory-limit 256 --dir-mode 0777 --file-mode 0666 --no-systemd"
    secretName: ci-s3-secret
