apiVersion: v2
name: traefik
description: m0sh1 Traefik wrapper chart based on the Docker Hardened Images Traefik chart
type: application
version: 0.1.8
appVersion: "3.7.5"
kubeVersion: ">=1.29.0-0"
home: https://traefik.io/traefik/
icon: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png
maintainers:
  - name: m0sh1
    email: yael@m0sh1.cc
sources:
  - https://github.com/traefik/traefik-helm-chart
  - https://git.m0sh1.cc/m0sh1/container-images/src/branch/main/docker/traefik
dependencies:
  - name: traefik-chart
    alias: traefik
    version: 41.0.2
    repository: oci://dhi.io
annotations:
  category: Networking
  licenses: Apache-2.0
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: traefik
      image: ghcr.io/isityael/traefik:5f2456c@sha256:5d8b4063b3ff0112d6075ad2128c37f3ea79b6beba2377c5a98c666d545f91fb
    - name: dhi-traefik
      image: dhi.io/traefik:3.7.5-alpine3.24@sha256:38126c9632cf7b93ad9db950323bb896a87c65048b3e3e99cd7aa16e5aaad7e8
  artifacthub.io/changes: |
    - kind: changed
      description: >-
        Stop rendering Gateway API CRDs; Gateway API v1.5.1 CRDs are now an external cluster prerequisite.
