matrixUmbrella:
  imageProfile: dhi
  imagePullSecrets:
    - name: docker-hardened-images

ess:
  image:
    pullSecrets:
      - name: docker-hardened-images
  matrixTools:
    image:
      pullSecrets:
        - name: docker-hardened-images
  haproxy:
    image:
      registry: dhi.io
      repository: haproxy
      tag: "3.4.1-debian13"
      digest: sha256:cc3bdcf4049e26efa76a225b1bfb7ae8d374ffa6ef6afb6c9304f1c085070990
      pullSecrets:
        - name: docker-hardened-images
  postgres:
    image:
      registry: dhi.io
      repository: postgres
      tag: "18.4-alpine3.22"
  redis:
    image:
      registry: dhi.io
      repository: valkey
      tag: "9.0.3-alpine3.22"

matrix-appservice-irc:
  waitForRedis:
    image:
      repository: dhi.io/busybox
      tag: "1.37.0-musl"
  postgres:
    image:
      repository: dhi.io/postgres
      tag: "18.4-alpine3.22"
  redis:
    image:
      repository: dhi.io/valkey
      tag: "9.0.3-alpine3.22"
