{{- $cnpg := .Values.cnpg | default dict -}}
{{- $cluster := $cnpg.cluster | default dict -}}
{{- $databases := $cnpg.databases | default list -}}
{{- if $cluster.enabled }}
{{- range $databases }}
{{- if .enabled }}
{{- $databaseName := toString .name -}}
{{- $metadataSuffix := regexReplaceAll "[^a-z0-9-]+" (lower $databaseName) "-" | trimAll "-" -}}
{{- $metadataName := printf "%s-%s" $cluster.name $metadataSuffix -}}
{{- if or (ne $metadataSuffix $databaseName) (gt (len $metadataName) 63) -}}
{{- $nameHash := sha256sum $databaseName | trunc 8 -}}
{{- $metadataName = printf "%s-%s" ($metadataName | trunc 54 | trimSuffix "-") $nameHash -}}
{{- end }}
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ $metadataName }}
  namespace: {{ $cluster.namespace }}
  labels:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/part-of: {{ $cluster.name }}
  {{- with $cnpg.databaseAnnotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  name: {{ .name | quote }}
  owner: {{ .owner | quote }}
  cluster:
    name: {{ $cluster.name | quote }}
  {{- if .databaseReclaimPolicy }}
  databaseReclaimPolicy: {{ .databaseReclaimPolicy | quote }}
  {{- end }}
  {{- if .extensions }}
  extensions:
{{ toYaml .extensions | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
