{{- if not .Values.runner.existingConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forgejo-runner.fullname" . }}-config
  labels:
    {{- include "forgejo-runner.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
{{ toYaml .Values.runner.config | nindent 4 }}
{{- end }}
