runner:
  instanceURL: https://forgejo.bogusdomain.test
  registrationTokenSecret: forgejo-runner-ci
  name: ci-runner
  baseLabels: docker:docker://ghcr.io/yaelmoshi/forgejo-job-alpine:3.23
  jobLabel: node22
  jobImage: node:22-bookworm

daemonConfig:
  registryMirrors:
    - https://mirror.bogusdomain.test
  features:
    buildkit: true

serviceAccount:
  create: true
  name: forgejo-runner-ci

persistence:
  enabled: true
  storageClass: test-storage-class
  size: 1Gi
