{{- if .Values.sendalerts.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "healthchecks.fullname" . }}-sendalerts
  labels:
    {{- include "healthchecks.labels" . | nindent 4 }}
    app.kubernetes.io/component: sendalerts
spec:
  replicas: {{ .Values.sendalerts.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "healthchecks.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: sendalerts
  template:
    metadata:
      labels:
        {{- include "healthchecks.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: sendalerts
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "healthchecks.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: sendalerts
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.sendalerts.command | nindent 12 }}
          env:
            {{- include "healthchecks.env" . | nindent 12 }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.sendalerts.resources | nindent 12 }}
{{- end }}
