apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homepage.fullname" . }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "homepage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "homepage.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "homepage.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: homepage
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: config-files
              mountPath: /app/config/bookmarks.yaml
              subPath: bookmarks.yaml
            - name: config-files
              mountPath: /app/config/services.yaml
              subPath: services.yaml
            - name: config-files
              mountPath: /app/config/widgets.yaml
              subPath: widgets.yaml
            - name: config-files
              mountPath: /app/config/settings.yaml
              subPath: settings.yaml
            - name: config-files
              mountPath: /app/config/kubernetes.yaml
              subPath: kubernetes.yaml
            - name: config-files
              mountPath: /app/config/docker.yaml
              subPath: docker.yaml
            {{- if or .Values.config.proxmox .Values.config.proxmoxString }}
            - name: config-files
              mountPath: /app/config/proxmox.yaml
              subPath: proxmox.yaml
            {{- end }}
            {{- if .Values.config.customCss }}
            - name: config-files
              mountPath: /app/config/custom.css
              subPath: custom.css
            {{- end }}
            {{- if .Values.config.customJs }}
            - name: config-files
              mountPath: /app/config/custom.js
              subPath: custom.js
            {{- end }}
            {{- range $filename, $_ := .Values.config.extraFiles }}
            - name: config-files
              mountPath: /app/config/{{ $filename }}
              subPath: {{ $filename }}
            {{- end }}
            - name: logs
              mountPath: /app/config/logs
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          emptyDir: {}
        - name: config-files
          configMap:
            name: {{ .Values.config.useExistingConfigMap | default (include "homepage.fullname" .) }}
        - name: logs
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
