# Default values for gitea-runner.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

# -- Docker-in-Docker sidecar container
dind:
  image:
    repository: docker
    tag: "29.4.3-dind-alpine3.23@sha256:685b91dca8eab7de1dce1c303dbb7a763e4082d6a60db10968adf3295fbd2495"
    pullPolicy: IfNotPresent
  args:
    - --host=unix:///var/run/docker.sock
    - --tls=false
  securityContext:
    privileged: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "2"
      memory: 4Gi

# -- Gitea Actions runner container
runner:
  image:
    repository: gitea/runner
    tag: "1.0.3@sha256:373d17d2bcd477a11c277b6ddd4cf6a14c29cc25cf579a0cbaa43a94dfc04f03"
    pullPolicy: IfNotPresent
  instanceURL: ""
  registrationTokenSecret: ""
  registrationTokenKey: REGISTRATION_TOKEN
  name: ""
  baseLabels: self-hosted
  jobLabel: ""
  jobImage: ""
  labels: ""
  dataMountPath: /data
  extraEnv: []
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    privileged: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 1Gi

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

daemonConfig:
  registryMirrors: []
  insecureRegistries: []
  features:
    buildkit: true

registryAuthSecret: ""
registryAuthSecretKey: .dockerconfigjson
registryAuthMountPath: /root/.docker/config.json

registryCASecret: ""
registryCAKey: ca.crt
registryCAMounts: []

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

nodeSelector: {}
tolerations: []
affinity: {}
