# Default values for gitea-runner.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

# -- Docker-in-Docker sidecar container
dind:
  image:
    repository: docker
    tag: "29.4.0-dind-alpine3.23@sha256:a6dd5322747a95cd8e3207bd8d415a8fd20ec34e9c00f06dc019cbd912013489"
    pullPolicy: IfNotPresent
  args:
    - --host=unix:///var/run/docker.sock
    - --tls=false
  securityContext:
    privileged: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "2"
      memory: 4Gi

# -- Gitea Actions runner container
runner:
  image:
    repository: gitea/act_runner
    tag: "0.4.1@sha256:696a59b51ad3d149521e3beb0229d5fb88f87295e1616f940199793274415b56"
    pullPolicy: IfNotPresent
  instanceURL: ""
  registrationTokenSecret: ""
  registrationTokenKey: REGISTRATION_TOKEN
  name: ""
  baseLabels: self-hosted
  jobLabel: ""
  jobImage: ""
  extraEnv: []
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    privileged: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 1Gi

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

daemonConfig:
  registryMirrors: []
  insecureRegistries: []
  features:
    buildkit: true

registryAuthSecret: ""
registryAuthSecretKey: .dockerconfigjson
registryAuthMountPath: /root/.docker/config.json

registryCASecret: ""
registryCAKey: ca.crt
registryCAMounts: []

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

nodeSelector: {}
tolerations: []
affinity: {}
