{{- if and (not .Values.secret.existingSecret) .Values.secret.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "searxng.fullname" . }}-secret
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
type: Opaque
stringData:
  SEARXNG_SECRET: {{ .Values.secret.value | quote }}
{{- end }}
